### ISSUE TITLE
dynamically add modules 

### ISSUE THREAD

**Issue by mastilver** [mastilver/modules-cdn-webpack-plugin#5]
- look for imported modules
- if path match `node_modules/<lib name>` then continue (should be careful to only match the `main`) 
- check if available in `module-to-cdn`
- ignore module?
- add to externals?
- add to assets

------
inspiration:
- https://github.com/webpack/webpack/blob/master/lib/IgnorePlugin.js
- https://github.com/jharris4/html-webpack-include-assets-plugin
- https://github.com/webpack/webpack/blob/master/lib/ExternalModuleFactoryPlugin.js

**Comment by mastilver** [comment]
closed by: https://github.com/mastilver/modules-cdn-webpack-plugin/commit/c3a000887e963344bbf6a6f580a2d14d7d436d67

@mjackson You mentioned in [this tweet](https://twitter.com/mjackson/status/870633815844077569) regarding the forked version of my repo, that you wanted it to be automated; DONE ;)

**Comment by mjackson** [comment]
:D This looks awesome!
