### ISSUE TITLE
Should add to `chunks` provided a flag

### ISSUE THREAD

**Issue by mastilver** [mastilver/modules-cdn-webpack-plugin#6]

**Comment by mastilver** [comment]
`modules-cdn-webpack-plugin` can now be used by a core webpack plugin

I added some docs for https://github.com/danethurber/webpack-manifest-plugin (https://github.com/mastilver/modules-cdn-webpack-plugin#usage-with-manifestplugin)

/cc @mjackson

**Comment by mjackson** [comment]
This looks great! My initial thought was that if the CDN URL were added to the original `chunks` array, then tools like `html-webpack-plugin` that read from that array would be able to automatically get them. In other words, we shouldn't need any code to specifically support `html-webpack-plugin` (just a theory, I don't really know).

e.g. in [the `html-webpack-plugin` docs](https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates) it says:

> htmlWebpackPlugin.files: a massaged representation of the assetsByChunkName attribute of webpack's stats object. It contains a mapping from entry point name to the bundle filename

Does that make sense?

**Comment by mastilver** [comment]
Yes it does make sense, but `html-webpack-plugin` mess up with `publicPath`, we have an open issue for it: https://github.com/jantimon/html-webpack-plugin/issues/613 but I thing I'm going to close it as it would make thing even more complex (I think)

**Comment by mastilver** [comment]
You can do a quick test by removing that condition, https://github.com/mastilver/modules-cdn-webpack-plugin/blob/master/src/index.js#L29, tests will fail!
